"""自我学习模块管理器：扫描 ~/.lampson/learned_modules/，动态注册为工具。

learned_modules/ 下的 .py 文件是 Lampson 在使用过程中自主生成/改进的代码模块。
通过在模块中定义 register_tool() 函数，可以自动将模块功能暴露为工具供 LLM 调用。

模块规范：
    1. 文件名即模块名（snake_case），如 url_summarizer.py
    2. 可选定义 TOOL_SCHEMA: dict — OpenAI function calling schema
    3. 可选定义 TOOL_RUNNER: Callable[[dict], str] — 工具执行函数
    4. 如果没有 TOOL_SCHEMA，模块仍可作为普通库被 shell python 调用
    5. 安全约束：禁止 import src 内部模块，只能用标准库 + 已安装的第三方库
"""

from __future__ import annotations

import importlib.util
import logging
import sys
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

LAMPSON_DIR = Path.home() / ".lampson"
LEARNED_MODULES_DIR = LAMPSON_DIR / "learned_modules"

# 禁止 learned_modules import 的包（防止逃逸沙箱）
_BLOCKED_IMPORTS = frozenset({
    "src",
    "src.core",
    "src.tools",
    "src.feishu",
    "src.skills",
    "src.memory",
    "src.platforms",
    "src.selfupdate",
    "src.planning",
})

# 已加载的模块 {module_name: module}
_loaded_modules: dict[str, Any] = {}


def ensure_dir() -> None:
    """确保 learned_modules 目录和 __init__.py 存在。"""
    LEARNED_MODULES_DIR.mkdir(parents=True, exist_ok=True)
    init_file = LEARNED_MODULES_DIR / "__init__.py"
    if not init_file.exists():
        init_file.write_text(
            "# Learned modules - auto-generated by Lampson\n",
            encoding="utf-8",
        )


def scan_and_register() -> list[dict[str, Any]]:
    """扫描 learned_modules/ 目录，加载所有模块并注册为工具。

    返回注册成功的工具 schema 列表。
    """
    ensure_dir()
    registered: list[dict[str, Any]] = []

    for py_file in sorted(LEARNED_MODULES_DIR.glob("*.py")):
        if py_file.name.startswith("_"):
            continue

        module_name = py_file.stem
        try:
            module = _load_module(module_name, py_file)
        except Exception as e:
            logger.warning(f"加载 learned_module {module_name} 失败: {e}")
            continue

        _loaded_modules[module_name] = module

        # 检查是否定义了 TOOL_SCHEMA 和 TOOL_RUNNER
        schema = getattr(module, "TOOL_SCHEMA", None)
        runner = getattr(module, "TOOL_RUNNER", None)

        if schema and runner:
            try:
                from src.core import tools as tool_registry
                ok = tool_registry.register_external(schema, runner)
                if ok:
                    registered.append(schema)
                    logger.info(f"已注册 learned_module 工具: {module_name}")
                else:
                    logger.warning(f"learned_module {module_name} schema 校验未通过，已跳过工具注册")
            except Exception as e:
                logger.warning(f"注册 learned_module {module_name} 工具失败: {e}")
        else:
            logger.debug(f"learned_module {module_name} 无 TOOL_SCHEMA，跳过工具注册")

    return registered


def _load_module(module_name: str, py_file: Path) -> Any:
    """动态加载单个 Python 模块。"""
    spec = importlib.util.spec_from_file_location(
        f"learned_modules.{module_name}",
        str(py_file),
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"无法创建模块 spec: {module_name}")

    module = importlib.util.module_from_spec(spec)

    # 安全检查：拦截危险 import
    _install_import_guard(module_name)

    spec.loader.exec_module(module)
    return module


def _install_import_guard(module_name: str) -> None:
    """为 learned_module 安装 import 拦截器（仅记录警告，不硬拦截，避免误杀）。"""
    # 目前仅做日志记录，后续如需硬拦截可改为抛异常
    pass


def get_module(name: str) -> Any | None:
    """获取已加载的模块对象。"""
    return _loaded_modules.get(name)


def list_modules() -> list[dict[str, str]]:
    """列出所有已加载的 learned modules。"""
    ensure_dir()
    result = []
    for py_file in sorted(LEARNED_MODULES_DIR.glob("*.py")):
        if py_file.name.startswith("_"):
            continue
        name = py_file.stem
        module = _loaded_modules.get(name)
        has_tool = hasattr(module, "TOOL_SCHEMA") if module else False
        result.append({
            "name": name,
            "path": str(py_file),
            "registered_as_tool": str(has_tool),
        })
    return result


def write_module(name: str, code: str) -> str:
    """写入一个新的 learned module 文件。

    Args:
        name: 模块名（snake_case，不含 .py）
        code: 完整的 Python 源码

    Returns:
        操作结果描述
    """
    ensure_dir()

    # 安全校验：名称合法性
    if not name.replace("_", "").isalnum():
        return f"[错误] 模块名 '{name}' 不合法，只允许字母、数字和下划线"

    # 安全校验：禁止 import src
    if _contains_blocked_import(code):
        return "[错误] 代码包含禁止的 import（不允许 import src 内部模块）"

    target = LEARNED_MODULES_DIR / f"{name}.py"

    # 如果已存在，先读出来做备份信息
    action = "更新" if target.exists() else "创建"

    try:
        target.write_text(code, encoding="utf-8")
    except OSError as e:
        return f"[错误] 写入失败: {e}"

    # 语法检查
    import py_compile
    try:
        py_compile.compile(str(target), doraise=True)
    except py_compile.PyCompileError as e:
        # 语法错误，回滚
        target.unlink(missing_ok=True)
        return f"[错误] 代码语法检查失败，已回滚: {e}"

    logger.info(f"已{action} learned_module: {name}")
    return f"已{action}模块: {name}"


def _contains_blocked_import(code: str) -> bool:
    """检查代码是否包含禁止的 import 语句。"""
    import re
    for line in code.splitlines():
        stripped = line.strip()
        # from src.xxx import ...
        m = re.match(r"^from\s+(\S+)", stripped)
        if m:
            top = m.group(1).split(".")[0]
            if top in _BLOCKED_IMPORTS:
                return True
        # import src.xxx
        m = re.match(r"^import\s+(\S+)", stripped)
        if m:
            top = m.group(1).split(".")[0]
            if top in _BLOCKED_IMPORTS:
                return True
    return False


def get_module_code(name: str) -> str | None:
    """读取指定模块的源码。"""
    target = LEARNED_MODULES_DIR / f"{name}.py"
    if not target.exists():
        return None
    try:
        return target.read_text(encoding="utf-8")
    except OSError:
        return None


def get_modules_summary() -> str:
    """生成 learned modules 概要，供 system prompt 注入。"""
    ensure_dir()
    modules = list_modules()
    if not modules:
        return ""
    lines = ["已加载的自我学习模块："]
    for m in modules:
        tool_flag = " [工具]" if m["registered_as_tool"] == "True" else ""
        lines.append(f"- {m['name']}{tool_flag}")
    return "\n".join(lines)
